[package]
name = "rust_mc_serv"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.45.0",  features = ["full"]}
flate2 = {version = "1.1.1"}
serde = {version = "1.0.219", features = ["derive"]}
serde_with = "3.12.0"
serde_json = "1.0.140"
