[package]
name = "rust_mc_serv"
version = "0.1.0"
edition = "2024"

[dependencies]
# async-trait = {version = "0.1.88", optional = true}
tokio = {version = "1.45.0",  features = ["full"]}

# [features]
# async = ["async-trait"]