[package]
name = "rust_minecraft_server"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_mc_proto = "0.1.19"
serde = { version = "1.0.219", features = ["derive"] } # used in text component
serde_json = "1.0.140"
serde_with = { version = "3.12.0", features = ["macros"] }